import Image from 'next/image'

import talent from '../public/images/image8.png'
import miami from '../public/images/image3.png'
import sectorGDP from '../public/images/image9.png'
import futureCompanies from '../public/images/image5.png'
import waterloo from '../public/images/image11.png'
import mansion from '../public/images/image1.png'
import stripeRemote from '../public/images/image10.png'
import nomad from '../public/images/image4.png'
import internet from '../public/images/image7.png'
import estonianRoon from '../public/images/image2.png'
import russia from '../public/images/image6.png'

export default function Body() {
  return (
    <div className='col-12 col-md-8 col-lg-6 pb-3'>
      <h1 id='smartyoungbc' className='pb-2'>Smart Young BC: A Vision for the Future of BC</h1>
      <p className='text-muted'>By Ian Vanagas</p>
      <p>A strong indicator that BC is moving in the right direction is if <b>smart young people are moving and staying here</b>. Why this metric compared to something like economic health, output, GDP, HDI, debt levels, prices, cultural output, global awards, or something else?</p>
      <ol start="1">
        <li>Many of these factors are out of the control of the province, they are tied to the Canadian or Global decisions more so than the provincial decisions. Provinces don't have much say in banking, international trade, or foreign affairs. We must focus on levers we can control.</li>
        <li>All of these factors are downstream of people. People create the economy, form companies, manage companies, create culture, and entertain. Without smart people continuing to come to BC, the economy and culture will stagnate. At the point this happens, it is too late to change. Pre-emptive action is needed to prevent this stagnation.</li>
      </ol>
      <blockquote>“People, ideas, machines — in that order!” - John Boyd.</blockquote>
      <h1 id='smart'>Smart</h1>
      <p>I focus on “smart” people because they have the largest impact on the economy and quality of life for the province as a whole. I define smart people as the top 5% of the most ambitious, creative, driven, and capable people in their given fields. These people are <a href='https://ianvanagas.com/2020/05/26/be-irreplaceable/' target='_blank'>irreplaceable</a>.</p>
      <blockquote>Why some countries stay at the cutting edge of science and emerging technologies is a complex question, the topic of countless books and historical studies. But one crucial factor is the sheer number of smart, talented people they have. - <a href='https://www.thenewatlantis.com/publications/the-egghead-gap' target='_blank'>Caleb Watney</a></blockquote>
      <p>Smart people take risks and build great things. They create research breakthroughs, cultural experiences, large employment opportunities, and more. In doing so, they dramatically improve the lives of the average British Columbian. The government mostly focuses on the average person who wants stability and consistency in their lives, and this should continue to be the case. Still, to create the best possible future, more focus can and should be put on attracting and supporting smart people than it currently is.</p>
      <blockquote>Superstar talent is the most precious resource in the process of producing innovation. The cost of capital is at an all-time low for governments, so plowing billions into the development of physical infrastructure is not in principle prohibitive. But the world's geniuses are inherently scarce, and so their choice of where to live and work is critical. The advantage to a country that attracts geniuses compounds over time, as clusters form around them — talent attracts more talent — which helps all the individuals and firms in such clusters become more productive than they would be in isolation. - <a href='https://www.thenewatlantis.com/publications/the-egghead-gap' target='_blank'>Caleb Watney</a></blockquote>
      <p>The government talks a lot about attracting the smartest possible people, but does relatively little. Their actions should better reflect their thoughts. They don't fully understand the upsides these people can bring. These people aren't just being good citizens and paying a lot of taxes. They are fundamentally shaping the present and the future of the province. If BC wants to continue to succeed as a province, we should care about attracting and retaining smart people here.</p>
      <p>A bonus point about smart people is that they want to be around other smart people. They are drawn toward and are <a href='https://ianvanagas.com/2022/03/28/encouragement-is-actually-important/' target='_blank'>encouraged</a> more because of each other. In this case, one plus one does equal three. Nearly all of the largest cultural and economic breakthroughs have happened because “<a href="https://twitter.com/visakanv/status/1153706486586994688?s=20" target='_blank'>scenes</a>” of smart people have been loosely connected in one place. They inspire and encourage each other to do more. BC, with the right focus, could create one of these scenes.</p>
      <h1 id='young'>Young</h1>
      <p>I am biased because I am a young person, so I want to live around people like me, but I think there are good reasons to focus on young people. I define young people as anyone between late high school and early career (16-26). </p>
      <p>First is the most practical reason, young people are the most likely to move. They are the least tied down by family, jobs, and other responsibilities. Many young people feel less tied down to a place than ever. This is great for locations that want to attract them, and bad for ones losing them. Convincing a young person to move is much easier (and cheaper) than convincing an old person to move. Once here, it becomes a lot easier to convince them to stay, than convince them to move here when they are older.</p>
      <p>Second, young people have the most potential and upside. They have most of their lives and careers ahead of them. They have the most energy and time available to work. They have a higher propensity for risk, and ultimately bold risks are what push society into the future. Although they may not have an economic or cultural impact now, the potential they have is limitless. They are the future of the province. The young people who are here now, become the leaders of the future.</p>
      <p>Third, young people can be swayed and influenced the most. They can jump between fields, and be persuaded into new and different areas. They are moldable and can spend their time working on different important problems. They have raw talent, brain power, and energy ready to be put to use in the industries of the future. With the right influence, they can set themselves up for success over the long term, and this means success for BC over the long term.</p>
      <h1 id='cant-win'>Where BC Can't Win</h1>
      <p>To understand how we can attract smart young people, first, we have to understand where we are at a disadvantage to the rest of the world and play to our strengths. BC has low salaries, few multinational companies, relatively bad weather, and a high cost of living, but we have some unique advantages to use.</p>
      <h2>Low Salaries</h2>
      <p>BC has relatively low salaries for top people compared to the competing regions. For example, both Seattle and San Francisco have significantly higher salaries in areas like tech and software development. On top of this, the Canadian dollar is generally weaker than the American one, making earning in the Canadian dollar less appealing. People get distracted by the fact that the salaries for these positions are well above the “average” or “median” salary for a worker in BC. We can't be focused on this. The top people create disproportionate amounts of value, we should care that we can't pay them competitively.</p>
      <Image src={talent} alt='Talent vs Cost' /> 
      <p className='text-muted text-center'>Source: <a href='https://www.cbre.us/-/media/cbre/countryunitedstates/us-research/major-reports/2021/scoring-tech-talent-media-folder/2021-scoring-tech-talent.pdf' target='_blank'>CBRE</a></p>
      <h2>Global Headquarters</h2>
      <p>Vancouver is not a hub for global headquarters. Out of the 13 Canadian companies in the <a href='https://fortune.com/global500/2021/search/?fg500_country=Canada' target='_blank'>2021 Fortune Global 500</a>, 0 were located in BC. It is a regional hub for Western Canada in many cases. It does have offices for the largest multinational companies, but it is not their main place of employment. The places we are competing with have those same companies, but with larger footprints.</p>
      <p>Global HQs are valuable not only because they employ large numbers of the most ambitious people, but also because they create talent for the entire ecosystem. If a young person wanted to progress up the career ladder in a specific company, it would probably be best for them to be at the HQ. A lack of large organizational HQs causes a lack of opportunity to progress. This leads to a shortage of senior talent, something that plagued BC in many industries.</p>
      <h2>Weather</h2>
      <p>The weather is moderate, but not a draw compared to many places around the world. The summer is beautiful, and the rest of the year doesn't get too cold, but it definitely isn't good. Winter is significantly better than other places in Canada, but those aren't all the places we are competing with. “Ski season” is nice, but doesn't appeal to everyone. When you are competing with the Southern United States (California, Austin, Miami) and remote work hubs across the world (Bali, Thailand, Portugal, Spain), it is hard to claim we have “good weather.”</p>
      <h2>Cost of Living</h2>
      <p>The cost of living in BC is extremely high. Vancouver has the <a href='https://www.mercer.com/newsroom/2020-cost-of-living.html' target='_blank'>highest cost of living</a> in Canada. Housing is the one in the news, but taxes are also significantly higher than in many places in Canada and the US (even the most famous “high tax” places like California). Gas is more expensive here than in <a href='https://www.vancouverisawesome.com/local-news/metro-vancouver-gas-prices-are-now-the-highest-in-north-america-5134293' target='_blank'>any place in North America</a>. Childcare is expensive and has constant supply shortages.</p>
      <p>Seemingly no amount of politicians saying “we are going to lower the cost of living” or “we are going to build affordable housing” actually makes it happen. Housing, especially in the larger cities like Vancouver and Victoria, seems to be a lost cause. So much energy has gone into the space with few benefits in return. </p>
      <p>In 2017, the provincial government promised 114,000 affordable housing units within 10 years, but <a href='https://www.policynote.ca/housing-promises/' target='_blank'>progress has been slow</a>. “Less than 10% of the 114,000 unit target has been completed as of April 2021, rising to 22% if we count units in progress. A large share is merely “initiated” rather than under construction and all categories should show progress almost a year later.” Vancouver still has the <a href='https://www.cbc.ca/news/canada/british-columbia/priced-out-rental-crisis-victoria-1.6390095' target='_blank'>highest rent prices</a> in Canada, Victoria is 14th. Vancouver is ranked <a href='http://www.demographia.com/dhi.pdf' target='_blank'>3rd last in affordable housing</a> in the world and has the <a href='https://dailyhive.com/vancouver/most-expensive-cities-home-construction-costs-building' target='_blank'>9th highest housing construction costs</a>.</p>
      <p>This is a bad sign for future changes in this area. A lot needs to dramatically change to make a difference. Building more housing cannot be our only focus. Other places have expensive housing too. Cheap housing is nice to have, not a need to have for the future success of the province. Other places like California, New York, Singapore, Australia, and London have all succeeded without “cheap” housing as a core value proposition.</p>
      <p>What this all means is that we can't compete in a lot of areas other places do. Money is the biggest one. We have to be innovative in the ways we can compete. We must think in ways others aren't to discover advantages others don't realize.</p>
      <h1 id='choose-bc'>The Path Forward: How To Get Smart Young People To Choose BC</h1>
      <blockquote>Everything the province is doing should try to make up for the fact that we can't possibly pay people as much, even in top jobs. We have to get talented people here in other ways.</blockquote>
      <p>Smart young people are important, places are competing hard for them, and BC has its disadvantages. The number of smart young people is finite. Competition for them is zero sum. Depending on a places' actions, they can gain or lose them. With all this, how do you get them to choose BC and stay here? This question breaks down into three key areas. We need to understand and answer:</p>
      <ol start="1">
        <li>Why are smart young people located here leaving? Get them to stay here.</li>
        <li>How do we get smart young people interested in coming here? Create interest in coming here.</li>
        <li>Once they are interested, how do we make it easy to come here? Make it as easy to come here.</li>
      </ol>
      <p>Another key factor is figuring out <b>at what point in their lives</b> these questions are being answered by people. When are they making up their mind to leave? When are they getting interested and moving here? Largely these questions are answered by people at two times we as a province should spend our energy on:</p>
      <ol start="1">
        <li>What do smart young people want to do after high school?</li>
        <li>What do smart young people want to do after University (and early in their career)?</li>
      </ol>
      <p>After these points, people aren't young anymore. They build more connections and ties to the places they've spent their early life. They've had some career success and built a network they don't want to abandon. They become more stuck to places they've chosen. They require much more money or status to move somewhere, something we lack compared to the places we are competing with.</p>
      <h2 id='positive-future'>BC Can Give Smart Young People the Positive Future They Seek</h2>
      <p>BC must provide a compelling vision for the future to encourage smart you people to come and stay here. A vision provides answers to smart young people about the future of the province and their lives. Although people don't say it, these answers are crucial for their decision to come and stay here.</p>
      <p>Many young people I speak to at these stages are a bit lost. They are pessimistic about possible futures, for many of the same reasons I explained above. This is not a good sign for a place (BC) that wants to attract or keep people. Few people want to move to a place they see as difficult to live in or moving in the wrong direction. Few people want to stay in a place with no future, especially when they have options elsewhere. They believe moving somewhere else might be the solution to their problem, and they might be right. If BC provides a compelling vision for the future and makes progress on making it a reality, their questions would have better answers and they'd be more likely to come and stay here.</p>
      <p>Other people I speak with aren't lost but blocked. They are prevented from achieving what they want to achieve here. They have a personal vision but can't accomplish it here. They are too young to have access to the opportunities they want but can move to find those opportunities elsewhere. The type of work they want to do isn't supported here but is supported elsewhere. These are also solvable problems. We should be able to provide similar opportunities to our top smart young people as other places.</p>
      <p>We are failing to give these people the answers they need to come and stay here, and by doing so, failing the future of the province. We need new answers for them, a new vision of the future, and new progress on making it a reality. The future of BC is being created now, and we want the best people possible to be working on it. Here's how we could make it happen.</p>
      <h2 id='important-people'>Have Important People Say We Want Smart Young People</h2>
      <p>To make this all work, leaders must want smart young people to move to and stay in BC. They must shout from the rooftops so everyone in BC, Canada, and the world can hear what we are doing.</p>
      <p>This provides a signal. Leadership must be bought into the vision of BC as a place where smart young people want to live and work. They must signal this buy-in internally and externally. They must influence other “stakeholders'' in the province to believe it is important. They must show smart young people in BC and beyond that this is the direction we are moving in.</p>
      <p>Saying “we want smart young people here” is the first step in making it happen. It rallies other leaders to do the same. It builds trust with smart young people debating staying here or coming here. It shows a vision of BC moving in the right direction.</p>
      <p>Francis Suarez, the Mayor of Miami, is a successful example of a politician doing this. He promoted Miami on social media to an influential group of entrepreneurs, investors, and “tech bros.” He met with them in Miami and helped convince them to move (low taxes, interesting culture, and amazing weather helped).</p>
      <div className='w-100 text-center'>
        <Image src={miami} alt='Francis Suarez: How Can I Help?' />
        <p className='text-muted'>Source: <a href='https://twitter.com/FrancisSuarez/status/1467178693525221377'>Francis Suarez on Twitter</a></p> 
      </div>
      <p>Too many important people in BC are inward-facing. They only care about the opinions of the people close to them and try to influence a local audience. We live in a global world now. The internet has connected everyone around the world. An important person's words can reach the whole world if they want to. You don't just have to tell the people of BC how good you are, you can tell the world how good BC is.</p>
      <p>Leaders of top organizations here should lead by example as well. Those leaders aren't just business people, but examples of British Columbians. Someone like <a href='https://twitter.com/awilkinson' target='_blank'>Andrew Wilkinson</a> has done massive amounts for the reputation of Victoria by being active in the community, online in tech and investing circles (with his company <a href='https://www.tinycapital.com/' target='_blank'>Tiny</a>), and an outspoken supporter of living there.</p>
      <p>This is low-hanging fruit for BC. Most important people and politicians only care about young people concerning low-skill employment, climate change, social justice, and housing. They spend their time talking about these issues. What if they instead cared about them as our economic and cultural future? Growing the number of smart young British Columbians will allow us to find better solutions to these concerns. It allows more people to work on those problems directly and more to help indirectly by growing the wealth of BC.</p>
      <h2 id='future-industries'>Focus On The Industries of The Future</h2>
      <p>The future of BC will come from the industries and companies of the future. We cannot expect our large, old companies to compete in the global market for smart young people when large companies in cities like Calgary, Toronto, Seattle, San Francisco, and others are paying more for similar roles and higher prestige. To attract top smart young people, we need either to convince them to create something great here or have great things they can help build here. We can't be looking at the past for these companies.</p>
      <p>The traditional economy of BC is strong, largely due to its collection of natural resources from mining, energy, and forestry. We have clean power from hydroelectric and good ports that create a connection with markets worldwide. Much of the province benefits from high real estate prices. There is plenty of construction across the province and lots of jobs to do it.</p>
      <p>Real estate development and services, mid-management at resource companies, finance, law, or “consulting” are common areas for smart young people to go into. These industries provide lots of jobs and attract talent within the province, but they don't attract the top worldwide talent. Every place has their version of them.</p>
      <div className='w-100 text-center'>
        <Image src={sectorGDP} alt='BC GDP by Sector' />
      </div>
      <p>If you believe that great people create great companies, and great companies create a great province, you must have your young smart talent building in industries of the future. That isn't the case for BC today. To make this more of a reality, the government should double down on winning industries and companies of the future. Some examples of the industries and BC companies of the future include:</p>
      <ul>
        <li>Biotech/Medtech: Zymeworks, PocketPills, Medimap, AbCellera, Precision NanoSystems, symvivo, Stemcell Technologies, Acuitas Therapeutics, Starfish Medical</li>
        <li>Agritech: Semios, Lucent BioSciences, Terramera</li>
        <li>Cleantech: Carbon Engineering, NexiiBuilds, General Fusion, Moment Energy</li>
        <li><a href='https://www.vantechjournal.com/p/vancouver-web3' target='_blank'>Crypto</a>: Dapper Labs, LayerZero, Utopia Labs, BlockStream, Netcoins, Manifold.xyz, Covalent, NFT artists</li>
        <li>Entertainment, Metaverse: Thinkific, EA, Phoenix Labs, Ziva Dynamics, Overstory Media Group, ILM, Atomic Cartoons, VR/AR industry, movies/VFX</li>
        <li>What are the resource companies of the future?</li>
      </ul>
      <p><a href='https://docs.google.com/spreadsheets/d/1SMy4EziCFdlHskazEoFTjDqh_nk2q8iSQqcZtXZ-sSc/edit?usp=sharing' target='_blank'>Updated list and links to BC's companies of the future</a>. Send me an <a href='mailto:ianvanagas@gmail.com?subject=Smart%20Young%20BC%20Company%20Recommendation' target='_blank'>email</a> if you have recommendations for more.</p>
      <div className='w-100 text-center'>
        <Image src={futureCompanies} alt='BC Companies of the future' />
      </div>
      <p>Many of these companies have succeeded by connecting BC's older industries to the future. BC's agriculture industry leads to its Agritech industry. Our movie industry leads to our metaverse industry. In doing so, the talent flows from the past into the future. We should look for more opportunities to make this happen. Use our natural and historical advantages as a springboard into the future. These companies are both the most appealing to smart young people worldwide and are building the future of BC today.</p>
      <p>The tech industry is the fastest growing sector in BC. There will be a <a href='https://biv.com/article/2022/02/tech-health-care-lead-job-growth-bc-forecasts-1m-openings-2031#:~:text=The%20latest%20B.C.%20Labour%20Market,created%20in%20the%20coming%20decade' target='_blank'>projected</a> “140,700 job openings in technology from 2021-31” which is an estimated 14% of new jobs in BC. <a href='https://www2.gov.bc.ca/assets/gov/data/statistics/business-industry-trade/industry/tech_profile_report.pdf' target='_blank'>As of 2019</a>, “B.C.'s high tech sector is responsible for generating around 6.6% of the province's total GDP.” Thirteen private BC tech companies have reached unicorn status of being valued at over $1B since December 2020. It is one of BC's top industries, but lags far behind tech industries in competing regions. It will need talent and capital to continue to scale.</p>
      <p>Entrepreneurs and investors of the future need to look where we can take our local historical advantages and scale them worldwide. Natural resources, such as forestry and mining, construction, and real estate are all massive markets critical to BC with global scale. Companies that create innovative technologies to help these industries here have a chance to become massive once their solution takes off worldwide. They can benefit from the talent and expertise in the industry here throughout their lifecycle. </p>
      <h3>Incentivize and Invest in These Industries</h3>
      <p>We must continue to invest in these industries, help new companies get started, and grow already successful companies. By providing more capital to these industries, more smart young people will be interested in working in them. We should move more subsidies, benefits, and credits from companies of the past to companies of the future. Cost of capital (lack of investors) and operating (rent, taxes) is higher here than in many other places, so BC needs to make sure these industries and companies can compete globally for the long term.</p>
      <p>The government both needs to get out of the way of top companies and support those companies in their growth. They should build deeper relationships to understand their needs and trust the leaders and markets in these industries to make good decisions. </p>
      <p>Venture investing is about taking calculated risks. Bureaucracies, like government organizations, hate taking risks. Startups move fast and change rapidly. Bureaucracies move slow and hate change. Making venture investment more bureaucratic and filled with rules is not a good way to invest in the future. Provide smart people opportunities to take more calculated risks, and the potential payoffs for them and the province as a whole will benefit.</p>
      <p>For example, <a href='https://www.inbcinvestment.ca/' target='_blank'>InBC</a> “is an independent $500 million strategic investment fund created by the Government of British Columbia. Our mandate is to help promising companies grow, while generating returns that benefit all British Columbians.” This is a lot of money that could go a long way at incentivizing the market for early-stage companies and investors of all types. Instead, it will be controlled by a large, bureaucratic, risk-averse organization with a mandate to secure “financial, environmental, and social impact.” I have no doubt that these people are smart and talented, but the structure is destined to be slow and fail because of the number of barriers they've put up.</p>
      <p>I have also heard from entrepreneurs here that they struggle with fundraising for a variety of reasons. Incentives like the <a href='https://www2.gov.bc.ca/gov/content/employment-business/investment-capital/venture-capital-programs' target='_blank'>Venture Capital Tax Credit Program</a> require strict and elaborate reporting requirements, treating the company almost as a public company. This often isn't worth it for founders because it requires them to spend time on financials rather than building the businesses. Venture capitalists in BC are also known to be <a href='https://alexdanco.com/2021/01/11/why-the-canadian-tech-scene-doesnt-work/' target='_blank'>risk averse</a>. They require better businesses and better terms to invest, causing many entrepreneurs to look elsewhere for funding.</p>
      <p>People at all levels hate failure. Founders, employees, startups, investors, and governments all don't want to fail. It is critical for BC's future success to let companies fail here. Failure is a part of the process. We must provide support where we can, in terms of capital and talent, and let success work itself out.</p>
      <h3>Showcase and Promote These Industries</h3>
      <p>On top of talent and capital, these industries need “energy” and “status.” We need to be excited about these industries as a province. Working at one of these companies needs to be seen as building the future. Your friends and family should be encouraging you to work as a blockchain developer rather than a big banking analyst.</p>
      <p>Creating hype around industries will attract more talent to them, both within the province and globally. Status plays a larger role in our decisions than we realize, and these industries are currently seen too poorly. The risk seems higher than the reward to many, and we should work to make this not the case.</p>
      <p>To raise the status of these industries, we have to raise their profile. We need more effort at multiple levels to promote these companies. Industry organizations like <a href='https://frontiercollective.net/' target='_blank'>Frontier Collective</a> should be expanded to raise the profile of industries through communications, stakeholder engagement, events, and more. Industry-specific local journalism like <a href='https://www.vantechjournal.com/' target='_blank'>Vancouver Tech Journal</a> and <a href='https://victechjournal.com/'  target='_blank'>Victoria Tech Journal</a> provides a high-quality channel and voice to these companies where they didn't have one before. We need more of both.</p>
      <p>These companies should be provided benefits (as many of them already are) in return for a focus on BC and speaking out about the value of BC. The leaders of these companies are the leaders of the future of BC, we should trust them to be our representatives on the world stage. Engage with the founders, online creators, and young entrepreneurs building and driving these companies. We need these industries, companies, and leaders to be influencing the talent of the future.</p>
      <h2 id='unblock'>Unblock and Unlock Younger Talent</h2>
      <p>Everywhere competes for senior experience talent. Everyone wants people with experience and reputation. This means these people usually flock towards the biggest markets, with the biggest companies, and get paid the most. BC does not have the luxury of competing here, but we do have the ability to compete for overlooked young talent.</p>
      <h3>Invest in Younger Talent</h3>
      <p>A lot of young talent across the world is “blocked” in many ways. They don't have the opportunities, connections, and support to do big things. They are forced into “traditional” paths of going to school and working their way up the career ladder when many could have a larger impact earlier. Some flock to areas where they could get more of these opportunities, usually big markets and startup hubs. This is mostly because these areas have a lot of opportunities in general, not that they specifically target these people.</p>
      <p>BC could create a new generation of smart young people by specifically targeting them and unlocking opportunities for them here. This could get more young people to stay here and others to come here. All this while inspiring new ideas and innovation within the economy and culture.</p>
      <p>An example of a way to invest in young talent is a high potential visa program. The UK has a high potential visa program for young people who graduate from Top 50 universities and have enough money to support themselves. Although BC has a <a href='https://www.welcomebc.ca/Immigrate-to-B-C/documents/BC-PNP-SI-EEBC-Program-Guide.aspx' target='_blank'>skilled immigrant program</a>, it requires work experience, employment offers in BC, high application fees, and is slow to process. What if we lowered the requirements for specific smart young people? Prove that you are smart and you can fend for yourself here and we should let you in.</p>
      <p>Another more radical example is a <a href='https://www.strangeloopcanon.com/p/on-medici-and-thiel' target='_blank'>Thiel Fellowship-like</a> program. What if BC said to the smartest young people in Canada: “we'll give you $100,000 to move here and do whatever you want. Make art, start a non-profit, do research, build a business.” It worked for Thiel, creating billions of dollars in business value and thousands of extremely high-paying jobs. Few of these programs exist, and fewer still are backed by governments. One example is Ryan Holmes' <a href='https://www.theleagueofinnovators.org/' target='_blank'>League of Innovators</a>, an accelerator program for entrepreneurs 25 or younger.</p>
      <p>Another example of unlocking younger talent is supporting “dropouts.” We've all heard the story about a smart young person who has a business idea, finds some success, drops out of school, and becomes a larger success. Often part of that story is moving from their college to the big city where they have access to more opportunities. Many smart young people are getting more comfortable with this path, but still see the US as the place to go afterwards. BC could be appealing to more of these people by providing more encouragement, talent, and funding within Universities. </p>
      <p>Many universities have entrepreneurship programs, like the <a href='https://www.uvic.ca/innovation/' target='_blank'>Coast Capital Innovation Centre</a> at UVic. How do we improve these institutions? The Innovation Centre has supported a number of key Victoria startups early such as <a href='https://www.cuboh.com/' target='_blank'>Cuboh</a>, <a href='https://www.mazumago.com/' target='_blank'>MazumaGo</a>, <a href='https://www.panienergy.com/'  target='_blank'>Pani Energy</a>, and <a href='https://www.vinnauto.com/ca' target='_blank'>VINN Automotive</a>. Connecting these early companies with talent might be a solution. The talent pool here is deeper than people realize but inefficient. University students don't know about the companies being formed around them, and could contribute more if they had the opportunity.</p>
      <p>Outside of business, young people are often similarly blocked. Young scientists worldwide are chronically underfunded. Look at the US' funding of scientists.</p>
      <blockquote>The NIH <a href='https://nexus.od.nih.gov/all/2015/03/25/age-of-investigator/' target='_blank'>allocates</a> just 2% of its funding to scientists 35 and younger with 98% of the funding going to those 36 and older. We should not be surprised then that the majority of even the most talented young scientists are not supported by the current structures and do not see their future in academia. - <a href='https://newscience.org/' target='_blank'>New Science</a></blockquote>
      <p>Young scientists create discoveries with high upside. They often are less tied to the “standard” ways of doing things. They are more able to experiment and discover radical new innovations. For example, a majority of Nobel Prizes for chemistry or physiology or machine were awarded to researchers for <a href='https://pubmed.ncbi.nlm.nih.gov/15754950/#:~:text=Analysis%20of%20available%20data%20on,and%2047.4%25%2C%20correspondingly).' target='_blank'>discoveries during their 30s</a>.</p>
      <blockquote>I strongly believe that the only way to encourage innovation is to give it to the young. The young have a great advantage in that they are ignorant. Because I think ignorance in science is very important. If you're like me and you know too much you can't try new things. I always work in fields of which I'm totally ignorant. - <a href='https://elizabethdzeng.com/2014/02/26/how-academia-and-publishing-are-destroying-scientific-innovation-a-conversation-with-sydney-brenner/' target='_blank'>Sydney Brenner</a></blockquote>
      <p>BC could support the funding of younger scientists. We could be the home of young scientists in the world. These young scientists may create more breakthroughs, we don't know because we haven't tried. We could unlock a new wave of talent that the world is missing out on because they are stuck in their ways. <a href='https://docs.google.com/spreadsheets/d/1LI3We4mLxaNmwnZKpfTiUl5S4oyh6acVQrM4eVI5u0w/edit#gid=0' target='_blank'>New institutions</a>, such as <a href='https://newscience.org/' target='_blank'>New Science</a>, provide an example on how:</p>
      <blockquote>New Science is a 501c3 research nonprofit with the mission to facilitate scientific breakthroughs by empowering the next generation of scientists and building the 21st century institutions of basic science.</blockquote>
      <p>Grants, tax breaks, and targeted funding are used as incentives in arts and culture, could we expand that to young people more generally? We should provide more grants to young scientists and researchers to explore radically new areas earlier in their career. Many will fail, but some will create radical discoveries. It could be an opportunity to build a better future.</p>
      <h3>Align Incentives Beyond University</h3>
      <p>Beyond scholarship, BC could unlock more talent here by aligning incentives throughout the education journey. Right now the interaction between the government, universities, and students is transactional. The government wants to educate its population, universities want to educate, and students want to get educated. Money flows between all three to make this happen. BC should shift its focus beyond just educating people, and into developing smart young talent.</p>
      <p>Too many smart young people leave BC after high school, and too many leave after University. High schoolers worldwide, and especially in BC, should want to go to University here. University students in BC should want to stay in BC to work or continue to study after they are done with their degree.</p>
      <div className='w-100 text-center'>
        <Image src={waterloo} alt='Moving to Waterloo' />
        <p className='text-muted'>Source: <a href='https://twitter.com/altluu/status/1415223821703946245'>Dan Luu on Twitter</a></p> 
      </div>
      <p>We need to think about all of the native BC high school students (and parents) who think going to the US is better. What you can do in the US, you should be able to do in BC. It is mostly about prestige and talent, not a quality of education. Providing more visions of the future for where this province is going would encourage more of them to stay. Having more companies and opportunities here they'd like to work for is critical too. Every talented BC high schooler that goes to a US college instead of a British Columbian one is a failure.</p>
      <p>Could we provide a benefit on costs to top students who plan to stay here? Student fees are high, could we lower them for some sort of promise to stay in BC after graduation? Could we exchange them for a return on salary once they graduate (like <a href='https://www.bloomtech.com/' target='_blank'>BloomTech</a> or other income share agreement-focused companies)? Graduates pay back the full amount if they leave, less if they stay in Canada, and even less if they stay in BC.</p>
      <p>We could even provide tuition rebates for working in industries of the future or starting a startup. Imagine encouraging young people to get into <a href='https://www.ycombinator.com/' target='_blank'>Y Combinator</a> or another similar accelerator, like the local <a href='https://www.theleagueofinnovators.org/' target='_blank'>League of Innovators</a>, by saying “we'll waive your tuition payments if you do.” <a href='https://www.european-funding-guide.eu/scholarship/2678-financial-support-norwegian-students-abroad' target='_blank'>Norway</a>, for example, provides funding to students if they return after their degree.  </p>
      <p>We should look at our Universities as a collection and make recommendations to students to move around. If top-tier talent isn't at top-tier institutions, it is missing out on its potential. What if we encouraged the young smart talent at second-tier universities to move to first-tier ones preemptively? This might be the encouragement they needed to stick around and pursue their career in BC further. They'd be encouraged to be more ambitious by better schools, and this would be better for them.</p>
      <p>Throughout the world, young people are blocked from pursuing the areas they want. BC could spend energy and capital trying to unblock and unlock smart young people. We could develop a high potential visa program, invest in ambitious young entrepreneurs and scientists, align education to the long term goals of the province, and more. If we do this successfully, smart young people will want to come here and stay here. They'd have opportunities to create radically new businesses, organizations, cultures, and science if they were less blocked by current processes. We'd be improving the future of our province (and the world).</p>
      <h2 id='connect'>Connect People More Aggressively</h2>
      <p>The more connections created here, the more attached people are to this place. It also makes it more likely people will find their culture, work, and social fit. These become more efficient when people know the breadth of opportunities here in BC.</p>
      <p>For smart young people, connection creates clusters. Clusters or scenes create incredible things. Ambitious people make the people they are connected to more ambitious. Connected smart people create new, exciting ideas. For example, the <a href='https://en.wikipedia.org/wiki/Homebrew_Computer_Club' target='_blank'>Homebrew Computer Club</a> led to the personal computing industry, including Apple. <a href='https://en.wikipedia.org/wiki/The_Inklings' target='_blank'>The Inklings</a> literary group led to J.R.R. Tolkien and C.S. Lewis publishing three of the best selling and most impactful fantasy series ever (The Lord of the Rings, The Hobbit, and The Chronicles of Narnia). All of these are things we want to happen in BC, so we should work to create more connections to do it.</p>
      <blockquote>Individuals immersed in a productive scenius will blossom and produce their best work. When buoyed by scenius, you act like genius [sic]. Your like-minded peers, and the entire environment inspire you. - <a href='https://kk.org/thetechnium/scenius-or-comm/' target='_blank'>Kevin Kelly</a></blockquote>
      <p>Some individuals and organizations take this into their own hands, but we need more of them doing this. We need people who want to <a href='https://ianvanagas.com/2022/02/03/how-to-create-social-capital-like-travis-kalanick/' target='_blank'>build massive amounts of social capital</a>. Social capital is critical for creating flourishing places.</p>
      <p>More connections need to be made at University, in the workplace, in key industries, and beyond. The talent and energy are here, I don't think a lot of people realize it. There needs to be a shift in culture and connection.</p>
      <h3>University</h3>
      <p>University is a key place where lifelong connections are built for young people. Universities are draws of talent. Every smart person wants to go to University unless they are exceptionally smart, or already know their path. The university experience may be entirely useless at teaching people more or preparing them to be future leaders, but it does do a good job at connecting people and building bonds to a specific location.</p>
      <blockquote>You should choose your college based on its network of students and the geographic network they inhabit more than course of study or sports teams. If you choose the right people to be around in college, they will open up ideas, relationships, jobs, aspirations, attitudes and resources that fit with you and a virtuous cycle will be set in motion. Your network will ask you to be your best self and live your best life, like a trainer at the gym. In this way, your college network will have an exponential impact on your life. - <a href='https://www.nfx.com/post/your-life-network-effects/' target='_blank'>James Currier</a></blockquote>
      <p>At university, smart people will be around each other and build ties with each other and the surrounding ecosystem. The more ties they build here, the more likely they are to stay. Although Universities stated goals are to teach people, their real goals are to create social ties. A lot of the value that is created by Universities in the form of social capital. We should be focusing more on that as much as possible.</p>
      <p>Universities pretend that teaching and testing are the most important things they do, and they spend time and money like it is. When people talk about university, they talk about their friends and the people they met there. Shouldn't this be a sign we should focus on making this better? Fund more events of all kinds. Connect new students, old students, alumni, community members, businesses, non-profits through the university ecosystem. Help students pursue the projects and opportunities most interesting to them. Each university can become more of a hub for connection than it already is.</p>
      <blockquote>I would say the main thing that universities do — which is the main thing that academia does — is to let people affiliate with credentially impressive people. That is, academia does have a very complicated, strong process for ranking people and saying who's more prestigious and who's more impressive, and it gives them an official label: this person is impressive. - <a href='https://epiphanyaweek.com/2018/11/19/speech-robin-hanson-explains-human-signaling/' target='_blank'>Robin Hanson</a></blockquote>
      <p>Speaking from experience, a university like UVic is a mixed bag in terms of connection. My business program did a good job connecting students, professors, and the broader community, through events, speakers, and cohort-based learning. Other programs weren't so lucky. I know many people who made friends with a group of people in first-year residences and didn't expand beyond throughout. Faculty were disconnected and interacted with each other little. There was no effort to connect people in different faculties together even if both groups could benefit. These people are missing out, and their university organizers are largely to blame.</p>
      <p>Another example of UVic's failure is alumni engagement. They don't do a nearly good enough job connecting alumni unless they want money from you. They see the only purpose of alumni as donations. They lack any vision larger than that, mostly because it isn't their job. There is so much social capital waiting to be created in alumni networks, and universities should be incentivized by the province (and citizens) to do it. Many alumni would rather give back time and energy, and feel a reward for doing it. A solution like <a href='https://www.covalent.live/' target='_blank'>Covalent</a> could help unlock some of it. They could learn a lot about building community.</p>
      <p>We should amp up the amount of money spent at Universities for social events with a specific focus on the <a href='#future-industries'>industries of the future</a>. Funding to student organizations to run events should be raised and tied to the number of people attending events. Students should be connected to the industry and cultural ecosystem around them. Businesses and organizations should be connected with students as well. All of these events and connections should continue beyond graduation. Work hard to create the ties that bind people to each other and BC, and they'll be more likely to stick around for the long term.</p>
      <h3>The Rest of the Time</h3>
      <p>Outside of Universities, we need more events where young people can meet each other. Where are the crypto, biotech, aerospace, agritech events specifically for young people? Industry-specific parties, ski or surf trips, shows, tournaments, and events. These aren't about shaking hands and exchanging business cards, they are about creating <a href='https://twitter.com/visakanv/status/1153706486586994688' target='_blank'>scenes</a> and clusters. If you know what smart people around you are working on, it makes you want to do things too.</p>
      <p>It is sad I never knew what was going on at other high schools, with other smart students, or at local universities during my time in high school. There are plenty of opportunities to connect the smartest young people even earlier. A key connection at this point in life can radically change the path of someone's life.</p>
      <blockquote>High school networks are especially important because they are influential when we are forming our identities and worldviews as young adults. High school networks are also correlated with academic achievement, work habits, and even college admission — defining access to future networks and building a vibrant life of your choosing. - <a href='https://www.nfx.com/post/your-life-network-effects/' target='_blank'>James Currier</a></blockquote>
      <p>Large companies should step up to connect their employees. Too many people don't know the good people inside their company. They don't know the career paths, things they can learn, and opportunities. The more young people know about the opportunities within their own companies, the more likely they are to find an area they're interested in. Solutions like <a href='http://www.randomcoffees.com/' target='_blank'>Random Coffees</a> exist. This isn't a uniquely BC problem but is something BC can solve if focused on.</p>
      <p>Outside of companies, industries as a whole need to focus on connecting. Compared to other places, the number of events and meetups is relatively low. The amount of buy-in and support from local companies is also relatively low. There are some big, well-funded companies here who do nothing to support events in the community. Key companies need to help fund events like these, even small amounts go a long way. </p>
      <p>A problem might be that the opportunities just don't exist. Local industry events and meetups are a flywheel: more events, more attendees, more connections, more value, more support. It is up to individuals to start and expand these events, but support from the province and the ecosystem would help.</p>
      <p>For example, people love conferences. I heard from Master's students that a key benefit for them was going to conferences (being paid for by Universities), travelling, and meeting people. This leads to many collaborations. BC has many wonderful places for conferences, being beautiful and having a massive tourism industry. We have conferences for industries of the past like <a href='https://www.pdconf.com/' target='_blank'>dentistry</a>, <a href='https://www.agricultureshow.net/' target='_blank'>agriculture</a>, and <a href='https://informaconnect.com/buildex-vancouver/' target='_blank'>building</a>. Where are the conferences for the industries of the future? Why couldn't we be the host of something like <a href='https://www.nft.nyc/' target='_blank'>NFT NYC</a> or <a href='https://www.ethdenver.com/' target='_blank'>ETHDenver</a> or its equivalent for the many different industries of the future?</p>
      <p>If BC were to connect the people we have here better than anywhere else, that becomes a competitive advantage. What other places are doing in terms of creating connections isn't particularly special. We can copy what works and amp it up. We can empower <a href='http://croker.harpethhall.org/Must%20Know/Psychology/WeisbergGladwell.pdf' target='_blank'>superconnectors</a>. If we make this a priority, the payoff is stronger roots, more social capital, better ideas, and a stronger BC.</p>
      <h2 id='bring-people'>Bring People Here By Any Means Necessary</h2>
      <p>Any way we can get people to come here is a good thing. Talent is the most important factor in the future success of BC. Bringing people here temporarily, promoting remote work, and making moving here easy are all ways we could get more people to spend time here and contribute their time, energy, talent, and money to developing and strengthening BC.</p>
      <p>BC is appealing as a destination. We are stable economically and politically, open to travellers, and have a more relaxed immigration policy than lots of places. BC has a diversity of cultures and people, all of which can support bringing more people here. Our openness and diversity are key differentiators for BC, so we should take full advantage of them.</p>
      <h3>Bring Young People Here Temporarily</h3>
      <p>Young people are less tethered to a location than ever before. Smart young people are travelling and moving a lot because it is so easy. BC should capitalize on this. There is so much value in bringing people even temporarily. They spend money here, benefit the people who are here by bringing their talent and knowledge, and might be convinced to stay here. They see the level of talent and energy here and want to come here more permanently.</p>
      <p>To bring more people here, we should host more events people want to travel for, especially for young people. Provide more money for them to come and stay here. Increase the number of high school, university, and company “exchanges.” We should promote more internships for our companies of the future, not only to people here but to people far away.</p>
      <p>In the longer term, often all young people need is housing and food. They need the basics covered and then can put their energy into building cool things. To help them with this, we should put money into housing smart young people. We could also lower the regulations on weird housing arrangements. Young people are more willing to live in worse conditions if it means they get to live in a good location, with good people, and save money.</p>
      <p>Where are the hacker houses and weird living arrangements for young people in BC? Could we provide more incentives to do this? I've heard of the massive overly expensive houses in Vancouver being filled up with people as a way to avoid the vacancy tax, but do they exist? <a href='https://twitter.com/BeeHousedao' target='_blank'>BeehouseDAO</a> is an example. They are trying to create the first Web3 Creator House DAO in Vancouver. We need to create more of these living arrangements with purposes. For example, there should be <a href='https://slimemoldtimemold.com/2022/02/17/charter-houses/' target='_blank'>charter houses</a> for entrepreneurs, writers, artists, researchers. Promote smart young people to come here and live in them.</p>
      <div className='w-100 text-center'>
        <Image src={mansion} alt='Spliting a Mansion for $1000' />
      </div>
      <p>Housing is a key blocker here, but young people are much more flexible on housing arrangements than old people are. We aren't talking about owning houses or housing a young family here. Young people are more willing to live with large groups of other people. They are more willing to live in worse conditions. If we aren't going to build them more housing, we should at least allow them to live in stranger ways.</p>
      <h3>Promote Remote Work</h3>
      <p>Remote work is a trend that took off during COVID, BC didn't do a good enough job capitalizing on it, but that doesn't mean it is too late. BC is beautiful, culturally diverse, has good food, many places are walkable, safe, and has opportunity. We have camping, skiing, water sports, golf, boats, beaches, events, cool neighbourhoods, craft beer, coffee, and more. This appeals to young people and we are good at showing it off. Our tourism industry is proof of this. More resources should be moved towards promoting BC as a remote work destination.</p>
      <p>Top global, future-focused companies like <a href='https://twitter.com/bchesky/status/1483474046847225865?s=20' target='_blank'>Airbnb</a>, Stripe, and <a href='https://blog.coinbase.com/4-reasons-coinbase-is-staying-remote-e48733832312' target='_blank'>Coinbase</a> have all focused increasingly on remote work. Their employees (and prospective employees) want it, and that is a good sign.</p>
      <div className='w-100 text-center'>
        <Image src={stripeRemote} alt='74% of Stripe hiring remotely' />
        <p className='text-muted'>Source: <a href='https://twitter.com/patrickc/status/1480647701221896195?s=20'>Patrick Collison on Twitter</a></p> 
      </div>
      <p>Remote work provides smart young people with the flexibility to work for great companies located elsewhere while benefiting from the culture and the beauty of BC. Remote workers are like super-tourists. They spend here and provide value to the people around them here.</p>
      <p>People who are here remote working are more likely to stay here and join or start companies here than people who aren't here. People who remote work here benefit the local community if they engage with it and meet people here. Maybe they'll work on projects with people locally, while continuing to benefit from the higher salaries provided by the global labour market.</p>
      <p>Many companies have been innovating in the remote work world, but few cities have followed. In the past few years, we've seen huge growth in short term rentals, co-working, services for nomads, global labour markets, virtual offices, and more. There is innovation to be done at the regional and provincial level to embrace these trends. BC could leverage its talent in tourism to innovate new ways to provide value to people who come here for remote work.</p>
      <p>For example, spending time on the beach, in the sun, surfing are all popular in the remote working world, but I feel that doing the same thing with skiing needs to be innovated. Resort towns should look to attract more remote workers. Let them know there is good internet, social life, cultural activities and skiing. Showcase the stories of people remote working there. Showcase how BC can be a year-round destination for remote work.</p>
      <p>Be appealing where young people are looking, mostly on the internet. BC should hire a vlogger just to go around BC showcasing its sites, YouTube and TikTok are king. There are already people doing this themselves, can the government enable them to go further? Create “bounties” and content for videos about BC. Engage young filmmakers across the province to create videos that showcase BC. We have a beautiful province, we should show it off more.</p>
      <p>We could put effort into making BC be the most reviewed place online, every restaurant, experience, shop has more reviews than any other place in the world. Make BC the most covered place on Wikipedia. Dominate SEO. Few governments are focusing on this, how many government officials even know what SEO is? We have to think like we are a company competing against other companies.</p>
      <p>To figure out what is working, cities around BC (and the province as a whole) should look at <a href='https://nomadlist.com/north-america' target='_blank'>Nomad List</a>. It is the key source of remote work location data. Many locations throughout BC should aim to be higher on its recommendation list than they are. It is surprising places like Whistler, Kelowna, Tofino, and ski resorts through the province are so far down. Look at the rankings for North America:</p>
      <div className='w-100 text-center'>
        <Image src={nomad} alt='NomadList North America Rankings' />
      </div>
      <p>To raise their rankings, we should be improving the areas they are ranking for. We should be asking for more reviews. It helps having important people letting the world know we are serious about remote work. Many of the areas we have little to no control over. A few areas we have more control over are safety, lack of crime, “liked by members,” walkability, friendly to foreigners, and importantly, internet.</p>
      <h3>Provide Good Internet Everywhere</h3>
      <p>Good internet makes a big difference. Good internet provides access to everyone (young and old, new and existing). It helps bridge the urban/rural divide if such a thing exists. Could the BC government subsidize <a href='https://www.starlink.com/' target='_blank'>StarLink</a> for citizens (especially if they are young)? Because of BC's mountainous geography, it would likely be cheaper than trying to run high-quality internet everywhere.</p>
      <div className='w-100 text-center'>
        <Image src={internet} alt='Internet coverage in BC' />
        <p className='text-muted'>BC's internet coverage and speeds. Brown is &gt;75% to 100% 50/10 Mbps, Orange is &gt;50% to 75% 50/10 Mbps.</p> 
      </div>
      <p>Better internet opens more of the province up to remote working. It would mean more potential areas to live, cheaper housing in rural areas. Internet access is a big deal to the smart young people of the future. If a place has slow internet, it is immediately out of contention. The internet plugs talent into the world. If talent isn't on the internet it is being wasted, it isn't living up to its potential.</p>
      <p>Because BC is so mountainous, it is tough to have cities everywhere. The infrastructure they need for critical resources like transportation, electricity, construction, and food isn't as good as large cities. Internet is an even lower level priority, but we should implement advances in telecommunications close that gap.</p>
      <h3>Make Moving Here Easy</h3>
      <p>Once you get people to come here temporarily or remote work here, lots of the hard work is done. We then need to make it easy for them to stay. If someone has an idea to come here to work, don't bog down their interest with paperwork and bureaucracy. Make it easy for someone to move here on a whim. It should be easier to move here as a smart young person than any place on the planet. Canada prides itself as a nation of immigrants, built by immigrants, we should be the best at immigration.</p>
      <p>Although the <a href='https://www.welcomebc.ca/Immigrate-to-B-C/B-C-Provincial-Nominee-Program' target='_blank'>provincial nominee program</a>, as well as the skilled and entrepreneur immigration program are on the right track, it has a <a href='https://www.welcomebc.ca/Immigrate-to-B-C/documents/BC-PNP-SI-EEBC-Program-Guide.aspx' target='_blank'>number of restrictions</a>. They include a combination of minimum amount of work experience needed, a job offer, completing school in BC, language proficiency tests, minimum income, and more. On top of all this, the <a href='https://www.welcomebc.ca/Immigrate-to-B-C/About-The-BC-PNP#ProcessingTimes' target='_blank'>processing times</a> are currently estimated at 3 months and <a href='https://www.welcomebc.ca/Immigrate-to-B-C/About-The-BC-PNP#Fees' target='_blank'>application fees</a> range from $1,150 to $3,500. In a world competing for this talent, this isn't good enough. We need to make it easier and faster for smart young people to come here.</p>
      <p>As a solution, look at what <a href='https://rebase.co/portugal' target='_blank'>Rebase</a> is doing for Portugal. They make it simple and appealing for foreigners, remote workers, and nomads to set up permanent residency in Portugal. They started in 2020 and are now responsible for about <a href='https://pca.st/episode/e54f7e0f-6b73-4434-b350-82446e0ef83e?t=1995' target='_blank'>~10% of people moving to Portugal</a>. Of the 50,000 people per year who move to Portugal, 4800-7200 use Rebase. It is helping reverse Portugal's massive brain drain and drawing large numbers of highly valuable talent to Portugal. Rebase has plans to expand to more countries like the UAE. Imagine what a program like this, but with government resources could do.  </p>
      <p>A big advantage for Canada and BC is that we support so much immigration. We are much more open to immigration than the US is. It's part of Canadian culture. The US had <a href='https://www.dhs.gov/immigration-statistics/special-reports/legal-immigration#:~:text=Lawful%20Permanent%20Residents,-Recent%20Trends&text=Nearly%20112%2C000%20noncitizens%20entered%20the,increase%20from%20FY%202021%20Q1.' target='_blank'>740,000 new permanent residents</a> in 2021 (~0.2% of their population), while Canada had <a href='https://www.canada.ca/en/immigration-refugees-citizenship/news/2021/12/canada-welcomes-the-most-immigrants-in-a-single-year-in-its-history.html' target='_blank'>401,000</a> (~1% of our population). There is a lot of opportunity here, we need more people to capitalize on them.</p>
      <p>Leverage the fact that Vancouver is the one big city in Canada in the same time zone as Seattle, LA, and SF. There are regular direct flights to each of them. American immigration laws are more strict than Canadian ones. There is a layer of talent who would like to be working in North America, especially for tech companies, but can't work in America because of immigration laws.</p>
      <div className='w-100 text-center'>
        <Image src={estonianRoon} alt='Weaponize Immigration' />
        <p className='text-muted'>Source: <a href='https://twitter.com/tszzl/status/1472740861213437957?s=20' target='_blank'>Roon</a> and <a href='https://twitter.com/seconds_0/status/1385021772529950722' target='_blank'>0.005 Seconds</a> on Twitter</p> 
      </div>
      <p>BC should leverage its stability to be a place people can come in a crisis. When a crisis happens, we should spend money to bring smart young people here. A lot of them could be self-sustaining once they get here, and are therefore only a plane ticket away. We have all types of cultures here that can provide support structures and help people integrate into BC and Canadian culture. Whenever there is a crisis or brain drain from somewhere, we should be at the top of the line supporting smart young people to come here and flourish.</p>
      <div className='w-100 text-center'>
        <Image src={russia} alt='Russian Immigration' />
        <p className='text-muted'>Source: <a href='https://twitter.com/kamilkazani/status/1501721290452963328' target='_blank'>Kamil Galeev on Twitter</a></p> 
      </div>
      <p>Once smart young people want to move to BC, we should let them and help them. We need these people for the future success of our province. We have to capitalize on the advantages we have, while we have them. Making it easy for talent to come here now will be critical to setting up BC for future success.</p>
      <h1 id='you-do'>What You Can Do</h1>
      <p>All of this doesn't happen with action. If you believe this is a valuable path forward you should tell people about it. Borrow and customize the ideas here to suit what you think is right.</p>
      <p>If you have any platform at all, letting smart young people know you want them to come to BC and stay in BC is valuable. Ask them what you can do as an individual or a leader to get them to stay. Share this, or ideas from this, with the world and see what it says.</p>
      <p>Figure out how what you spend your time on relates to industries of the future. What companies are up and coming in your industry? What companies in your industry are smart people attracted to? What can you do to support these companies? Talk about them, recommend people work for them, raise the status of them, become their partner or customer, invest in them, work for them yourself.</p>
      <p>When was the last time you supported or took a chance on a smart young person? There could be smart young people around you that are blocked and could use your support. Could organizations you are involved invest more into smart young people through internships, mentorship, grants, accelerators, or some other way?</p>
      <p>Could you be a better connection node to those around you? Could you or your organization connect the smart young people better? What scenes or clusters are you a part of and what could you do to make them better? Could you contribute more to events being run at local Universities, places you are an alumni at, in your industry, at local high schools, within your company, conferences?</p>
      <p>You should tell the smart young people you know to come to BC, and help them come here. Have a place they can crash? Encourage people all over to come to the events we have here. Know of people living in weird ways? Help it happen more if you can. Fund a charter house, support deregulation of housing, or the streamlining of immigration. Encourage the remote workers you know to spend some time in BC. Tell people how fun BC is to remote work from. Review and talk about your favourite BC places online. Lobby your government to improve internet access. If you can, make immigration easier and support the immigrants around you. Connect them with people you know, help them find opportunities here.</p>
      <h3>Actions You Can Take</h3>
      <p>A summary of actions you can take:</p>
      <ol start="1">
        <li>Share this with two people who might find it interesting. Share ideas from this in group chats you are a part of. Share this article on social media (<a href='https://twitter.com/intent/tweet?text=https%3A//www.smartyoungbc.com/' target='_blank'>Twitter</a>, <a href='https://www.facebook.com/sharer/sharer.php?u=https%3A//www.smartyoungbc.com/' target='_blank'>Facebook</a>, <a href='http://www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fsmartyoungbc.com%2F&title='>LinkedIn</a>). Tell important people around you that this is a future you want for BC.</li>
        <li>Ask yourself what you can personally do to bring and keep more smart young people to BC (and do it).</li>
        <li>Learn about the companies of the future in your industry. Here's <a href='https://docs.google.com/spreadsheets/d/1SMy4EziCFdlHskazEoFTjDqh_nk2q8iSQqcZtXZ-sSc/edit' target='_blank'>a list of them</a>. Talk about them, recommend people work for them, raise the status of them, become their partner or customer, invest in them, work for them yourself.</li>
        <li>Take a chance on a smart young person. See what you can do to unblock them. Invest in them through internships, mentorship, grants, accelerators, or something else. Help them with a visa, job recommendation, or accommodation. <a href='https://marginalrevolution.com/marginalrevolution/2018/10/high-return-activity-raising-others-aspirations.html'>Raise their aspirations</a>. Convince them to stay here.</li>
        <li>Connect people around you more. Meet new people. Contribute to events in your organization, university, local high schools, industry, conferences, especially if smart young people are there.</li>
        <li>Promote remote work. Tell remote workers you know to come here. Showcase how good BC can be, take a photo and share it online. Support and review local businesses and areas. Host immigrants and visitors, meet and connect with visitors. Create new types of accommodation.</li>
        <li>Lobby the government to deregulate housing, improve internet access, invest in communities of the future, provide funding to young people, and support and streamline more high skill immigration. An email to a city councillor, mayor, <a href='https://www.leg.bc.ca/learn-about-us/members'>MLA</a>, or <a href='https://www.ourcommons.ca/members/en'>MP</a> goes a long way (they get less thoughtful comments than you expect). Make sure to follow up.</li>
      </ol>
      <h1 id='end'>End</h1>
      <p>If you've made it this far, I'd love to hear from you. <a href='mailto:ianvanagas@gmail.com?subject=Smart%20Young%20BC' target='_blank'>Email</a> or <a href='https://twitter.com/IanVanagas' target='_blank'>message me</a> any feedback or ideas you have or if you'd like to meet to talk more about this (I respond to every message). My goal is to increase the number of smart young people in BC, and I want the best ideas to help do that. If you are taking any of the actions above, let me know how it goes.</p>
      <p>Add your email below to get more updates:</p>
      <iframe src="https://smartyoungbc.substack.com/embed" className='w-100' height="320" style={{border:"1px solid #EEE", background:"white", frameborder:"0", scrolling:"no"}}></iframe>
      <p>Thanks to Thomas Hollands, Georgiy Sekretaryuk, Arthur Lee, Mihai Lapuste, and Luisa Muniz for their feedback, recommendations, and encouragement.</p>
    </div>
  )
}
